[package]
name = "green-tools"
version = "0.1.0"
edition = "2021"
authors = ["urlordjames <32751441+urlordjames@users.noreply.github.com>"]
readme = "README.md"
description = "tools to assist with green-updater using green-lib"
license = "GPL-3.0+"

[dependencies]
tokio = { version = "1.20", default-features = false, features = [ "macros", "rt-multi-thread" ] }
green-lib = { git = "https://github.com/urlordjames/green-lib.git", version = "0.2" }
serde_json = "1"
sha2 = "0.10"
clap = { version = "3.2", features = [ "derive" ] }
url = "2.2"
lazy_static = "1.4"

[profile.release]
lto = "fat"
