name: "build"

on: ["push", "pull_request"]

jobs:
  build-macos:
    runs-on: "macos-latest"

    steps:
    - uses: actions/checkout@v2

    - name: "build"
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    
    - name: "prepare dist folder"
      run: |
        mkdir dist
        cp target/release/green-update dist
        cp target/release/green-manifest dist
    
    - uses: actions/upload-artifact@v3
      with:
        name: "macos"
        path: "dist/*"
        if-no-files-found: error

  build-deb:
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v2

    - name: "install cargo-deb"
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: cargo-deb

    - name: "build"
      uses: actions-rs/cargo@v1
      with:
        command: deb

    - name: "list stuff"
      run: ls target -lR
