name: "build"

on: ["push", "pull_request"]

jobs:
  build-macos:
    runs-on: "macos-latest"

    steps:
    - uses: actions/checkout@v2

    - name: "build"
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    
    - name: "prepare dist folder"
      run: |
        mkdir dist
        cp target/release/update dist
        cp target/release/manifest dist
    
    - uses: actions/upload-artifact@v3
      with:
        name: "macos"
        path: "dist/*"
        if-no-files-found: error